apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: processing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: processing
  name: spark-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: processing
subjects:
- kind: ServiceAccount
  name: spark
  namespace: processing
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io

