version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks: 
      - serasa-challenge
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks: 
      - serasa-challenge
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks: 
      - serasa-challenge
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  jupyter-spark:
        image: jupyter/pyspark-notebook:spark-3.1.2
        networks:
            - serasa-challenge
        ports:
          - "8888:8888"
          - "4040-4080:4040-4080"
        volumes:
          - ../notebooks:/home/jovyan/work/notebooks/
          - ../spark/resources/data:/home/jovyan/work/spark/data/
          - ../spark/resources/jars:/home/jovyan/work/spark/jars/
  minio:
        restart: always
        image: minio/minio@sha256:b36dbf66046daa79a1cdc6b1a35e0e7724e3b12ee21d528c8952c30b7984c1bb
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server /data --console-address ':9001' --address ':9000'
        environment:
            - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
            - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
        volumes:
            - minio_data:/data
        networks: 
          - serasa-challenge

  scylladb:
        image: scylladb/scylla
        ports:
            - "9042:9042"
            - "7005:7000"
            - "7001:7001"
            - "7199:7199"
            - "9160:9160"
        environment:
            - SCYLLA_ENABLE=3_11
            - SCYLLA_USER_API_PORT=10000
            - SCYLLA_RPC_PORT=9160
            - SCYLLA_STORAGE_PORT=7000
            - SCYLLA_INTER_NODE_PORT=7001
            - SCYLLA_HINTS_PORT=8080
        networks: 
          - serasa-challenge

volumes:
  minio_data:

networks: 
  serasa-challenge:
    driver: bridge